aliases: []
creation_timestamp: 1752920031106
current_stage: None
description: null
last_updated_timestamp: 1752920031106
name: sentiment_analysis_pipeline
run_id: 8e8ab2a9c89648f58f8946aad0dd3bfe
run_link: null
source: file:///content/Practica/mlflow/955277643914825373/8e8ab2a9c89648f58f8946aad0dd3bfe/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/955277643914825373/8e8ab2a9c89648f58f8946aad0dd3bfe/artifacts/sentiment_analysis
user_id: null
version: 4
