aliases: []
creation_timestamp: 1753294272139
current_stage: None
description: null
last_updated_timestamp: 1753294272139
name: sentiment_analysis_pipeline
run_id: 112e9e123eb84dc8a59a3ab4e9ecb436
run_link: null
source: file:///content/Practica/mlflow/454408747366455150/112e9e123eb84dc8a59a3ab4e9ecb436/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/454408747366455150/112e9e123eb84dc8a59a3ab4e9ecb436/artifacts/sentiment_analysis
user_id: null
version: 5
